name: MyWorkflow
on: push
env:
 test: ${{ vars.name }}
jobs: 
  DevJob:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Printing name
      run: echo "My Variable value is ${{ vars.name }}"
    - name: Printing Secret 
      run: echo "${{ secrets.apipass }}"
    - name: Printing Env variables
      run: echo "${{ env.test }}"
  QAJob:
    runs-on: ubuntu-latest
    environment: Qa
    steps:
    - name: Printing name
      run: echo "My Variable value is ${{ vars.name }}"
    - name: Printing Env variables
      run: echo "${{ env.test }}"
  StgeJob:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
    - name: Printing name
      run: echo "My Variable value is ${{ vars.name }}"
    - name: Printing Env variables
      run: echo "${{ env.test }}"
